/*


 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/nginx-operator/pkg/client/clientset/versioned/typed/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCacheV1alpha1 struct {
	*testing.Fake
}

func (c *FakeCacheV1alpha1) Ats(namespace string) v1alpha1.AtInterface {
	return &FakeAts{c, namespace}
}

func (c *FakeCacheV1alpha1) Nginx(namespace string) v1alpha1.NginxInterface {
	return &FakeNginx{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCacheV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
