/*


 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/nginx-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNginx implements NginxInterface
type FakeNginx struct {
	Fake *FakeCacheV1alpha1
	ns   string
}

var nginxResource = v1alpha1.SchemeGroupVersion.WithResource("nginx")

var nginxKind = v1alpha1.SchemeGroupVersion.WithKind("Nginx")

// Get takes name of the nginx, and returns the corresponding nginx object, and an error if there is any.
func (c *FakeNginx) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Nginx, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nginxResource, c.ns, name), &v1alpha1.Nginx{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Nginx), err
}

// List takes label and field selectors, and returns the list of Nginx that match those selectors.
func (c *FakeNginx) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NginxList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nginxResource, nginxKind, c.ns, opts), &v1alpha1.NginxList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NginxList{ListMeta: obj.(*v1alpha1.NginxList).ListMeta}
	for _, item := range obj.(*v1alpha1.NginxList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nginx.
func (c *FakeNginx) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nginxResource, c.ns, opts))

}

// Create takes the representation of a nginx and creates it.  Returns the server's representation of the nginx, and an error, if there is any.
func (c *FakeNginx) Create(ctx context.Context, nginx *v1alpha1.Nginx, opts v1.CreateOptions) (result *v1alpha1.Nginx, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nginxResource, c.ns, nginx), &v1alpha1.Nginx{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Nginx), err
}

// Update takes the representation of a nginx and updates it. Returns the server's representation of the nginx, and an error, if there is any.
func (c *FakeNginx) Update(ctx context.Context, nginx *v1alpha1.Nginx, opts v1.UpdateOptions) (result *v1alpha1.Nginx, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nginxResource, c.ns, nginx), &v1alpha1.Nginx{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Nginx), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNginx) UpdateStatus(ctx context.Context, nginx *v1alpha1.Nginx, opts v1.UpdateOptions) (*v1alpha1.Nginx, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nginxResource, "status", c.ns, nginx), &v1alpha1.Nginx{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Nginx), err
}

// Delete takes name of the nginx and deletes it. Returns an error if one occurs.
func (c *FakeNginx) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(nginxResource, c.ns, name, opts), &v1alpha1.Nginx{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNginx) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nginxResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NginxList{})
	return err
}

// Patch applies the patch and returns the patched nginx.
func (c *FakeNginx) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Nginx, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nginxResource, c.ns, name, pt, data, subresources...), &v1alpha1.Nginx{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Nginx), err
}
