/*


 */

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	cachev1alpha1 "github.com/nginx-operator/api/v1alpha1"
	versioned "github.com/nginx-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nginx-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/nginx-operator/pkg/client/listers/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AtInformer provides access to a shared informer and lister for
// Ats.
type AtInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AtLister
}

type atInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAtInformer constructs a new informer for At type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAtInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAtInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAtInformer constructs a new informer for At type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAtInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CacheV1alpha1().Ats(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CacheV1alpha1().Ats(namespace).Watch(context.TODO(), options)
			},
		},
		&cachev1alpha1.At{},
		resyncPeriod,
		indexers,
	)
}

func (f *atInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAtInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *atInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cachev1alpha1.At{}, f.defaultInformer)
}

func (f *atInformer) Lister() v1alpha1.AtLister {
	return v1alpha1.NewAtLister(f.Informer().GetIndexer())
}
