/*


 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/nginx-operator/api/v1alpha1"
	scheme "github.com/nginx-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NginxGetter has a method to return a NginxInterface.
// A group's client should implement this interface.
type NginxGetter interface {
	Nginx(namespace string) NginxInterface
}

// NginxInterface has methods to work with Nginx resources.
type NginxInterface interface {
	Create(ctx context.Context, nginx *v1alpha1.Nginx, opts v1.CreateOptions) (*v1alpha1.Nginx, error)
	Update(ctx context.Context, nginx *v1alpha1.Nginx, opts v1.UpdateOptions) (*v1alpha1.Nginx, error)
	UpdateStatus(ctx context.Context, nginx *v1alpha1.Nginx, opts v1.UpdateOptions) (*v1alpha1.Nginx, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Nginx, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NginxList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Nginx, err error)
	NginxExpansion
}

// nginx implements NginxInterface
type nginx struct {
	client rest.Interface
	ns     string
}

// newNginx returns a Nginx
func newNginx(c *CacheV1alpha1Client, namespace string) *nginx {
	return &nginx{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nginx, and returns the corresponding nginx object, and an error if there is any.
func (c *nginx) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Nginx, err error) {
	result = &v1alpha1.Nginx{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nginx").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Nginx that match those selectors.
func (c *nginx) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NginxList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NginxList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nginx").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nginx.
func (c *nginx) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nginx").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nginx and creates it.  Returns the server's representation of the nginx, and an error, if there is any.
func (c *nginx) Create(ctx context.Context, nginx *v1alpha1.Nginx, opts v1.CreateOptions) (result *v1alpha1.Nginx, err error) {
	result = &v1alpha1.Nginx{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nginx").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nginx).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nginx and updates it. Returns the server's representation of the nginx, and an error, if there is any.
func (c *nginx) Update(ctx context.Context, nginx *v1alpha1.Nginx, opts v1.UpdateOptions) (result *v1alpha1.Nginx, err error) {
	result = &v1alpha1.Nginx{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nginx").
		Name(nginx.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nginx).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nginx) UpdateStatus(ctx context.Context, nginx *v1alpha1.Nginx, opts v1.UpdateOptions) (result *v1alpha1.Nginx, err error) {
	result = &v1alpha1.Nginx{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nginx").
		Name(nginx.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nginx).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nginx and deletes it. Returns an error if one occurs.
func (c *nginx) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nginx").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nginx) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nginx").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nginx.
func (c *nginx) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Nginx, err error) {
	result = &v1alpha1.Nginx{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nginx").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
