/*


 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AtListerExpansion allows custom methods to be added to
// AtLister.
type AtListerExpansion interface{}

// AtNamespaceListerExpansion allows custom methods to be added to
// AtNamespaceLister.
type AtNamespaceListerExpansion interface{}

// NginxListerExpansion allows custom methods to be added to
// NginxLister.
type NginxListerExpansion interface{}

// NginxNamespaceListerExpansion allows custom methods to be added to
// NginxNamespaceLister.
type NginxNamespaceListerExpansion interface{}
